export { navigation as navigationPage } from './navigation'
export { footer as footerPage } from './footer'
export { home as homePage } from './home'
export { employee as employeePage } from './employee'
export { about as aboutPage } from './about'
export { contact as contactPage } from './contact'
export { candidates as candidatesPage } from './candidates'
