export { navigation as navigationPage } from './navigation'
export { footer as footerPage } from './footer'
export { home as homePage } from './home'
export { employees as employeesPage } from './employees'
export { about as aboutPage } from './about'
export { contact as contactPage } from './contact'
export { candidates as candidatesPage } from './candidates'
export { jobs as jobsPage } from './jobs'
export { jobDetail as jobDetailPage } from './jobDetail'
export { logos } from './logos'
