import {
    ChevronRight,
    Computer,
    PersonPinCircle,
    Person2,
    CheckCircleOutline,
    LinkedIn,
    Instagram,
    Menu,
    Wallet,
    PlaceOutlined,
    ArrowForwardIosSharp,
    Close,
    AttachFile,
    Delete,
    Business,
    BusinessCenter,
    Help,
    HomeWork,
} from '@mui/icons-material'

export const IconsMapper: Record<string, React.ComponentType> = {
    chevronRight: ChevronRight,
    computer: Computer,
    pin: PersonPinCircle,
    location: PlaceOutlined,
    person: Person2,
    checkCircleOutline: CheckCircleOutline,
    linkedIn: LinkedIn,
    instagram: Instagram,
    menu: Menu,
    wallet: Wallet,
    expandMore: ArrowForwardIosSharp,
    close: Close,
    attachFile: AttachFile,
    delete: Delete,
    business: Business,
    businessCenter: BusinessCenter,
    help: Help,
    homeWork: HomeWork,
}
