export type IconName =
    | 'chevronRight'
    | 'pin'
    | 'person'
    | 'computer'
    | 'checkCircleOutline'
    | 'linkedIn'
    | 'instagram'
    | 'menu'
    | 'wallet'
    | 'location'
    | 'expandMore'
    | 'close'
    | 'attachFile'
    | 'delete'
